### ISSUE TITLE
Path rewrite for external datasets

### ISSUE THREAD

**Issue by boyangzhao** [pritchardlabatpsu/cnp_dev#22]
With the use of external datasets, this requires the folders to be inside the DepMap folder. We can make this more flexible by custom defining where the parent folder for the external datasets is by not using `dir_depmap`, and let the full path be defined by the input param.

https://github.com/pritchardlabatpsu/cnp_dev/blob/69c97b964bee0a4d11aa237dcf072cee65fe49da/src/ceres_infer/data.py#L492-L493

Proposing as,
```
dm_data_ext.dir_datasets = ext_data['dir_datasets']
dm_data_ext.dir_ceres_datasets = ext_data['dir_ceres_datasets']
```
And for actual runs where the CERES data is different, but the genomic data is the same, at runtime, the param would look like (for PC9 for example),
```
ext_data = {'dir_datesets': '../datasets/DepMap',
            'dir_ceres_datasets': '../datasets/PC9',
            ...}
```

**Comment by ryy1221** [comment]
Hi Bo, I ran the code in the new branch and confirm that the corrected path works fine.
