### ISSUE TITLE
Remove PC9 after data preprocessing

### ISSUE THREAD

**Issue by ryy1221** [pritchardlabatpsu/cnp_dev#23]
Dropping the PC9 cell line before data preprocessing requires a deep copy of the whole DepMap folder. To make this more flexible, we can drop the branch cell line after data preprocessing.
https://github.com/pritchardlabatpsu/cnp_dev/blob/69c97b964bee0a4d11aa237dcf072cee65fe49da/notebooks/R8-format_PC9_and_To_data-YR.ipynb#L36-L39

Propose changes in data.py(pseudocode):
```
if external_name  == 'data_pc9':  
    for dataframes in dm_data_match_ext:
         dm_data_match_ext.dataframes.drop(PC9 cell line ID)
```
I will create and branch to do this then open a pull request.

**Comment by ryy1221** [comment]
Hi Bo,
I added a chunck of code to drop PC9 in data.py and confirmed that PC9 is removed from dm_data_match_pc9.pkl. 

https://github.com/pritchardlabatpsu/cnp_dev/blob/0ceda037d6a4549f5b5b6485cac36fd6f1720f94/src/ceres_infer/data.py#L292-L299

https://github.com/pritchardlabatpsu/cnp_dev/blob/0ceda037d6a4549f5b5b6485cac36fd6f1720f94/src/ceres_infer/data.py#L522-L523

**Comment by boyangzhao** [comment]
Can we make this more generic, as a `drop_cell_line(self, cell_line)`? Also we should make sure this post-drop is the same as the pre-drop in the other values? I think the pre-processing should depend on it...

**Comment by ryy1221** [comment]
Gotcha!

**Comment by ryy1221** [comment]
Hi Bo, looking at baseline filter stats, the features left of df_mut and df_rnaseq are slightly different between pre and post dropping, because pre-dropping would change the calculated threshold. But both have no affect on df_crispr.
Post dropping:
```
 source counts_invariant counts_cat_lowvariant counts_cont_lowvariant counts_nonexpressed feats_left
0	ceres	0	NaN	0.0	NaN	18333
1	mutation	19890	29635.0	NaN	NaN	9065
2	lineage	7	8.0	NaN	NaN	18
3	rnaseq	7531	NaN	5756.0	8630.0	36759
4	cn	0	NaN	0.0	NaN	27639
```
Predropping:
```
	source counts_invariant counts_cat_lowvariant counts_cont_lowvariant counts_nonexpressed feats_left
0	ceres	0	NaN	0.0	NaN	18333
1	mutation	19894	29642.0	NaN	NaN	9054
2	lineage	7	8.0	NaN	NaN	18
3	rnaseq	7531	NaN	5765.0	8626.0	36754
4	cn	0	NaN	0.0	NaN	27639
```

**Comment by boyangzhao** [comment]
ok - then there is data leakage if we were to do via post-dropping. Let's keep as pre-dropping then. We can propose other ways of transforming the data later.
