### ISSUE TITLE
Remove Q4 processing for external data

### ISSUE THREAD

**Issue by ryy1221** [pritchardlabatpsu/cnp_dev#26]
Q4 preprocessing is unnecessary for external data, except for Sanger. Therefore, I propose to add additional conditional statements for Q4 preprocessing:

1. After the preprocessing of Q3 data, the Q4 preprocessing will only execute when there is no external data or the external data is Sanger. 
https://github.com/pritchardlabatpsu/cnp_dev/blob/59b326b133b68a2582730aa71ba0dadf20c7c4ee/src/ceres_infer/data.py#L462-L466
2. Then, If external data exists, the external data preprocessing will execute.
https://github.com/pritchardlabatpsu/cnp_dev/blob/59b326b133b68a2582730aa71ba0dadf20c7c4ee/src/ceres_infer/data.py#L486-L489

In addition, redundant q3 processing was removed by getting the q3 sample index before filtering:
before:
https://github.com/pritchardlabatpsu/cnp_dev/blob/43b6b9c640e39401692488a3fc13538e2f7925de/src/ceres_infer/data.py#L460-L467
after:
https://github.com/pritchardlabatpsu/cnp_dev/blob/59b326b133b68a2582730aa71ba0dadf20c7c4ee/src/ceres_infer/data.py#L452-L456

**Comment by boyangzhao** [comment]
The first point on q4 preprocessing - this is to be addressed in the new class. For the redundant q3, agreed.
