### ISSUE TITLE
Get rid of 'random cell line name' hack

### ISSUE THREAD

**Issue by ryy1221** [pritchardlabatpsu/cnp_dev#27]
To get through the sample_filtering function, which only keeps cell line names that are in Q3, I assigned random Q3 cell line names for external data. This naming method might lead to confusion. 
Therefore I propose to remove the sample_filtering of crispr data frame for the external data, except for Sanger data.

1. A new parameter 'ext' is added in filter_samples. Only when ext is None, the filtering for df_crispr will execute. Because we don't want to filter the external cell lines out:
https://github.com/pritchardlabatpsu/cnp_dev/blob/59b326b133b68a2582730aa71ba0dadf20c7c4ee/src/ceres_infer/data.py#L173-L179

2. If the external data is sanger data, then the filtering will still carry out. If it's other external data, a value will be passed to ext parameter.
https://github.com/pritchardlabatpsu/cnp_dev/blob/59b326b133b68a2582730aa71ba0dadf20c7c4ee/src/ceres_infer/data.py#L499-L503

This will cause the external data be kept for crispr dataframe, but not for other dataframes: 
For example, in PC9:
![image](https://user-images.githubusercontent.com/32322852/126409879-153af5fe-5c19-4b13-8a08-cfe42559d3f9.png)

**Comment by boyangzhao** [comment]
I'd suggest to be a bit more generic, and not to restrict to Sanger data per se. Also a bit of conditionals in the method to still try to figure out if and when to include all the processing. It's better to be more explicit. One idea is to have a method for `process_standard` (the Q3), `process_new` (the Q4, which requires list of cell lines to be excluded, e.g. to Q3) and `process_external` (and this can have an argument apply filter_samples or not).

We can update the notebooks accordingly. And for the previous runs (we run all three methods), for the PC9 we run process_standard and process_external (with no filter samples).

**Comment by ryy1221** [comment]
I like the idea to have separate methods. 
For `process_new` and `process_external`, the `dm_data` and the `sample_q3` will be loaded for filtering.
https://github.com/pritchardlabatpsu/cnp_dev/blob/c921e9826c9a22ed426212f4cd62948859e999ef/src/ceres_infer/data.py#L520-L522
I also changed the parameters to be a dictionary. 
https://github.com/pritchardlabatpsu/cnp_dev/blob/c921e9826c9a22ed426212f4cd62948859e999ef/notebooks/Rrun01a-preprocess_PC9-YR.ipynb#L46-L49

**Comment by boyangzhao** [comment]
Please review on the new commits with class structure instead. The `filter_samples` you've added a new argument `ext`, which then decides on whether or not to match cell lines also for ceres data. I've removed this - as the conditionals is being controlled with the `match_cell_lines` argument for `process_external`. Please confirm

**Comment by ryy1221** [comment]
Thanks for adding the structure! There's no problem with the code. The only small thing is that by removing the `ext` in `filter_samples`, the other data frames except for crispr won't be filtered for external data. For PC9,  this results in：
![image](https://user-images.githubusercontent.com/32322852/126719766-0d994c72-6795-4370-a4da-814137e71716.png)

But it should not have any effect on the model, so I'm fine with this.

**Comment by boyangzhao** [comment]
In that case, let's get rid of the conditionals, and pass into the method `process_external` the list of cell lines to match? The list can be samples_q3, or in the case for Pc9 the list passed in is a list of one consisting of [cell line name].

**Comment by boyangzhao** [comment]
See latest commit for a proposed change. Does the PC9 have a cell line name? See the preprocess PC9 notebook (as part of commit), last cell `proc.process_external(match_samples_lst=['PC9'])`, I've put 'PC9' as the list value as placeholder.

**Comment by ryy1221** [comment]
`shared_idx` is None for external data. `samples_idx = list(set(self.shared_idx) & set(samples_idx))` in `filter_samples` make sthe `sample_idx` become None as well, therefore the external data will be filtered. This come back to passing an additional parameter?
I named it PC9 for it's the most straightforward name.

**Comment by boyangzhao** [comment]
Thanks - good point. I added an argument `shared_only` to `filter_samples`. Yes this adds an additional arguments, but are kept with default values. 

Updates are in
https://github.com/pritchardlabatpsu/cnp_dev/blob/bffa34fc6032fe818ff6ca294fd119d7a9787e2e/src/ceres_infer/data.py#L161-L176

And minor changes to process_external. The notebook for PC9 is updated in last cell to demonstrate how it works as of this change.

**Comment by boyangzhao** [comment]
And also, for the notebook PC9 processing, the processing is the same for both Brunello PC9 and L200 standalone, right? Right now only last cell (for standalone) has been updated with `proc.process_external(match_samples=['PC9'], shared_only=False)`

**Comment by ryy1221** [comment]
I think `shared_only` argument is necessary, but the `sample_idx` for external data (which is ['PC9']) will raise a keyError when selecting dataframes other than `df_crispr`. 
I don't want to make this more complicated... but my idea is: For the `shared_only == False` data, clear the dataframes with exceptions.
1. If there is no shared samples between `df_crispr` and other data frames, the `df_crispr` will be marked to excluded from filtering.  The `filter_exlude` could be used for other dataframes in the future
https://github.com/pritchardlabatpsu/cnp_dev/blob/3a852e2fea74f82ac1c05d1306b56386b9064510/src/ceres_infer/data.py#L155-L158
2. For `shared_only == False`, clear the dataframes with the exception of CERES
https://github.com/pritchardlabatpsu/cnp_dev/blob/3a852e2fea74f82ac1c05d1306b56386b9064510/src/ceres_infer/data.py#L172-L190

**Comment by boyangzhao** [comment]
Ah yes, for the keyerror. I've tried to simplify the `if shared_only ... else` into a simpler by adding a pd_filter method (this is essentially a pd.loc method, but a safe method that does not throw key errors, but instead gracefully ignore the unfound keys).

https://github.com/pritchardlabatpsu/cnp_dev/blob/b6ce2035b5ef1a19a625aa0a5be097d9d4b40cb9/src/ceres_infer/data.py#L172-L177

**Comment by ryy1221** [comment]
Yes this looks much better now. Then I think this issue is solved. I updated the preprocess notebooks.

**Comment by boyangzhao** [comment]
Awesome! And thanks for the minor fixes. I presume then you've done the runs and all is working. Results are same? As for the older processing notebooks (run01 processing and processing Sanger), I see you've created a new proc_data folder (presumably for testing purposes), shall we keep the old folder names (`20.0925 proc_data` for sanger, and `20.0817 proc_data` for standard) without the need to rerun, especially if we confirm the resulting processed datasets are the same? This way, the reference to the modeling notebooks remain the same.

**Comment by ryy1221** [comment]
Yes, the `21.0722` run is the run using the modified preprocess functions. 
Can you share your Sanger folder with me? The Sanger data on my end may be incomplete for some reason. My gene_effect file is extremely small and my Sanger output only left 2 cell lines, but in `20.0925 proc_data`, there are 151 cell lines remaining. 
Other than that, the preprocessed files all remain the same. I will update the folder names to the old ones.

**Comment by boyangzhao** [comment]
I've shared with you folders 19Q3 and 19Q4 (in /data/DepMap/). The proc_data folders in /out, I've already shared before.

**Comment by ryy1221** [comment]
Thanks. All preprocessed data are confirmed to be the same and I've renamed the folder names to previous ones.

**Comment by boyangzhao** [comment]
Super! Let's merge into revision?
